version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   depends_on:
  #     - mediamtx
  #   networks:
  #     - campy_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/campy
    depends_on:
      - db
    networks:
      - campy_network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campy_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - campy_network

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554/tcp"  # RTSP
      - "8888:8888/tcp"  # API
      - "8889:8889/tcp"  # WebRTC
      - "8083:8083/tcp"  # HLS
      - "8189:8189/udp"  # WebRTC UDP
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
    networks:
      - campy_network

networks:
  campy_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  storage: 