"""Initial migration

Revision ID: 4a2b6c2075ed
Revises: 
Create Date: 2025-03-09 21:10:35.246658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2b6c2075ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('rtsp_url', sa.String(), nullable=False),
    sa.Column('resolution', sa.JSON(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('codec', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cameras', sa.JSON(), nullable=False),
    sa.Column('storage', sa.JSON(), nullable=False),
    sa.Column('system', sa.JSON(), nullable=False),
    sa.Column('network', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('cameras')
    # ### end Alembic commands ###
